//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TumblrSync
{
    using System;
    using System.Collections.Generic;
    
    public partial class tDownload
    {
        public int id { get; set; }
        public Nullable<int> tBlogID { get; set; }
        public Nullable<int> jsPostID { get; set; }
        public string URL { get; set; }
        public string SystemPath { get; set; }
        public string WebPath { get; set; }
        public string Downloaded { get; set; }
        public string Filename { get; set; }
        public Nullable<System.Guid> PostLinkID { get; set; }
    }
}
