//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TumblrSync
{
    using System;
    using System.Collections.Generic;
    
    public partial class TumblrReblog
    {
        public int Id { get; set; }
        public int tbPostId { get; set; }
        public string tree_html { get; set; }
        public string comment { get; set; }
    
        public virtual TumblrPost TumblrPost { get; set; }
    }
}
