//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TumblrSync
{
    using System;
    using System.Collections.Generic;
    
    public partial class TumblrTag
    {
        public TumblrTag()
        {
            this.TumblrPosts = new HashSet<TumblrPost>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<TumblrPost> TumblrPosts { get; set; }
    }
}
