//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TumblrDownloader
{
    using System;
    using System.Collections.Generic;
    
    public partial class tAccount
    {
        public tAccount()
        {
            this.tBlogs = new HashSet<tBlog>();
        }
    
        public int id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string ConsumerKey { get; set; }
        public string ConsumerSecret { get; set; }
        public string systemDrive { get; set; }
        public string AccountSystemPath { get; set; }
        public string AccountWebPath { get; set; }
    
        public virtual ICollection<tBlog> tBlogs { get; set; }
    }
}
