//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TumblrDownloader
{
    using System;
    using System.Collections.Generic;
    
    public partial class TumblrPostOtherMedia
    {
        public int id { get; set; }
        public int tbPostId { get; set; }
        public string Type { get; set; }
        public string HDDPath { get; set; }
    
        public virtual TumblrPost TumblrPost { get; set; }
    }
}
