//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TumblrDownloader
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TumblrModel : DbContext
    {
        public TumblrModel()
            : base("name=TumblrModel")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tAccount> tAccounts { get; set; }
        public DbSet<tBlog> tBlogs { get; set; }
        public DbSet<tDownload> tDownloads { get; set; }
        public DbSet<TumblrAltSize> TumblrAltSizes { get; set; }
        public DbSet<TumblrBlog> TumblrBlogs { get; set; }
        public DbSet<TumblrOriginalSize> TumblrOriginalSizes { get; set; }
        public DbSet<TumblrPhoto> TumblrPhotos { get; set; }
        public DbSet<TumblrPlayer> TumblrPlayers { get; set; }
        public DbSet<TumblrPost> TumblrPosts { get; set; }
        public DbSet<TumblrPostComment> TumblrPostComments { get; set; }
        public DbSet<TumblrPostOtherMedia> TumblrPostOtherMedias { get; set; }
        public DbSet<TumblrReblog> TumblrReblogs { get; set; }
        public DbSet<TumblrTag> TumblrTags { get; set; }
    }
}
