//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TumblrDownloader
{
    using System;
    using System.Collections.Generic;
    
    public partial class TumblrBlog
    {
        public TumblrBlog()
        {
            this.TumblrPosts = new HashSet<TumblrPost>();
        }
    
        public int Id { get; set; }
        public string title { get; set; }
        public string name { get; set; }
        public int posts { get; set; }
        public string url { get; set; }
        public int updated { get; set; }
        public string description { get; set; }
        public int is_nsfw { get; set; }
        public int ask { get; set; }
        public string ask_page_title { get; set; }
        public int ask_anon { get; set; }
        public string submission_page_title { get; set; }
        public int share_likes { get; set; }
    
        public virtual ICollection<TumblrPost> TumblrPosts { get; set; }
    }
}
