//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TumblrDownloader
{
    using System;
    using System.Collections.Generic;
    
    public partial class TumblrPostComment
    {
        public int id { get; set; }
        public int tbPostid { get; set; }
        public System.DateTime Datetime { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string body { get; set; }
    
        public virtual TumblrPost TumblrPost { get; set; }
    }
}
