//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TumblrDownloader
{
    using System;
    using System.Collections.Generic;
    
    public partial class TumblrPhoto
    {
        public TumblrPhoto()
        {
            this.TumblrAltSizes = new HashSet<TumblrAltSize>();
            this.TumblrOriginalSizes = new HashSet<TumblrOriginalSize>();
        }
    
        public int Id { get; set; }
        public int tbPostId { get; set; }
        public string caption { get; set; }
        public int ExifId { get; set; }
        public string Downloaded { get; set; }
    
        public virtual ICollection<TumblrAltSize> TumblrAltSizes { get; set; }
        public virtual ICollection<TumblrOriginalSize> TumblrOriginalSizes { get; set; }
        public virtual TumblrPost TumblrPost { get; set; }
    }
}
