//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TumblrDownloader
{
    using System;
    using System.Collections.Generic;
    
    public partial class TumblrOriginalSize
    {
        public int Id { get; set; }
        public int tbPhotoId { get; set; }
        public int width { get; set; }
        public int height { get; set; }
        public string url { get; set; }
        public string LocalURL { get; set; }
        public string Downloaded { get; set; }
        public string SystemPath { get; set; }
        public Nullable<System.DateTime> DateDownloaded { get; set; }
    
        public virtual TumblrPhoto TumblrPhoto { get; set; }
    }
}
